In [1]:
import numpy as np

In [2]:
myarray = np.array([[1,2,3]], np.int64)

In [3]:
myarray

array([[1, 2, 3]], dtype=int64)

In [4]:
myarray[0,1]

2

In [5]:
myarray.shape

(1, 3)

In [6]:
myarray.dtype

dtype('int64')

In [7]:
listarray = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [8]:
listarray.dtype

dtype('int32')

In [9]:
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
listarray.size

9

In [11]:
listarray.shape

(3, 3)

In [12]:
zeroes = np.zeros((2,5))   # makes array of zeroes

In [13]:
zeroes

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
rng = np.arange(15)

In [15]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [16]:
lspace = np.linspace(1,5,12)

In [17]:
lspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [18]:
emp = np.empty((4,6))

In [19]:
emp

array([[4.67296746e-307, 1.69121121e-306, 1.60218491e-306,
        1.89146896e-307, 7.56571288e-307, 3.11525958e-307],
       [1.24610723e-306, 8.45593934e-307, 9.34600963e-307,
        2.22518251e-306, 1.33511969e-306, 1.78019761e-306],
       [9.34608432e-307, 1.33512376e-306, 1.11261570e-306,
        3.56027436e-307, 1.37961641e-306, 8.34424342e-308],
       [1.51317924e-306, 1.33508031e-306, 1.60219170e-306,
        8.90124610e-308, 0.00000000e+000, 0.00000000e+000]])

In [20]:
emp_like = np.empty_like(lspace)

In [21]:
emp_like

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [22]:
ide = np.identity(10)

In [23]:
ide

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [24]:
ide.shape

(10, 10)

In [25]:
arr = np.arange(99)

In [26]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [27]:
arr = arr.reshape(3,33)

In [28]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [29]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [30]:
x = [[1,2,3],[4,5,6],[7,8,9]]

In [31]:
ar = np.array(x)

In [32]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
ar.sum(axis=0)

array([12, 15, 18])

In [34]:
ar.sum(axis=1)

array([ 6, 15, 24])

In [35]:
ar.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [36]:
for i in ar.flat:
    print(i)

1
2
3
4
5
6
7
8
9


In [37]:
ar.ndim

2

In [38]:
ar.size

9

In [39]:
ar.nbytes

36

In [40]:
ar.argmax()

8

In [41]:
ar.argmin()

0

In [43]:
one = np.array([7,1,4,6,9])

In [44]:
one.argsort()

array([1, 2, 3, 0, 4], dtype=int64)

In [45]:
ar.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [46]:
ar.argmax(axis=0)

array([2, 2, 2], dtype=int64)

In [47]:
ar.argmax(axis=1)

array([2, 2, 2], dtype=int64)

In [49]:
ar2 = np.array([[1, 4, 0],
                [2, 0, 1],
                [5, 2, 7]])

In [50]:
ar + ar2

array([[ 2,  6,  3],
       [ 6,  5,  7],
       [12, 10, 16]])

In [51]:
ar*ar2

array([[ 1,  8,  0],
       [ 8,  0,  6],
       [35, 16, 63]])

In [53]:
ar-ar2

array([[ 0, -2,  3],
       [ 2,  5,  5],
       [ 2,  6,  2]])

In [55]:
ar2/ar

array([[1.        , 2.        , 0.        ],
       [0.5       , 0.        , 0.16666667],
       [0.71428571, 0.25      , 0.77777778]])

In [56]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [57]:
ar.sum()

45

In [58]:
ar.max()

9

In [59]:
ar.min()

1

In [67]:
np.where(ar2>1)

(array([0, 1, 2, 2, 2], dtype=int64), array([1, 0, 0, 1, 2], dtype=int64))

In [65]:
ar2

array([[1, 4, 0],
       [2, 0, 1],
       [5, 2, 7]])

In [68]:
np.count_nonzero(ar2)

7

In [70]:
np.nonzero(ar2)

(array([0, 0, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 0, 2, 0, 1, 2], dtype=int64))

In [71]:
import sys

In [72]:
py_ar = [23,2,43,67,1]

In [73]:
np_ar = np.array(py_ar)

In [74]:
sys.getsizeof(1) * len(py_ar)

140

In [76]:
np_ar.itemsize * np_ar.size

20

In [77]:
ar.tolist()

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]