In [1]:
import numpy as np

1. Write a Python program to convert a list of numeric value into a one-dimensional NumPy array.


In [2]:
py_list = [12.23, 13.32, 100, 36.32]
np_ar = np.array(py_list)
np_ar

array([ 12.23,  13.32, 100.  ,  36.32])

2. Create a 3x3 matrix with values ranging from 2 to 10.

In [3]:
ar = np.arange(2,11).reshape(3,3)
ar

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

3. Write a Python program to create a null vector of size 10 and update sixth value to 11.

In [4]:
ar1 = np.zeros(10)
ar1[6] = 11
ar1

array([ 0.,  0.,  0.,  0.,  0.,  0., 11.,  0.,  0.,  0.])

4. Write a Python program to reverse an array (first element becomes last).

In [5]:
ar2 = np.array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37])
ar2 = np.flip(ar2)
ar2


array([37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21,
       20, 19, 18, 17, 16, 15, 14, 13, 12])

5. Write a Python program to create a 2d array with 1 on the border and 0 inside.


In [6]:
ar3 = np.ones([5,5])
ar3[1:-1,1:-1] = 0
ar3

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

6. Write a Python program to add a border (filled with 0's) around an existing array

In [7]:
ar_ones = np.ones([3,3])
ar_zeroes = np.zeros([5,5])
ar_zeroes[1:-1,1:-1] = ar_ones
ar_zeroes

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

7. Write a Python program to create a 8x8 matrix and fill it with a checkerboard pattern.

In [8]:
checkerboard = np.zeros([8,8], dtype=int)
for i in range(8):
    for j in range(8):
        if (i+j) % 2 == 1:
            checkerboard[i][j] = 1
checkerboard

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

8. Write a Python program to convert a list and tuple into arrays.

In [9]:
li = [1, 2, 3, 4, 5, 6, 7, 8]
ar = np.array(li)
ar

array([1, 2, 3, 4, 5, 6, 7, 8])

In [10]:
tu = ([8, 4, 6],[1, 2, 3])
ar = np.array(tu)
ar

array([[8, 4, 6],
       [1, 2, 3]])

9. Write a Python program to append values to the end of an array

In [11]:
ar1 = np.array([10,20,30])
ar2 = np.arange(40,100,10)

ar2 = np.append(ar1,ar2)
ar2

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

10. Write a Python program to find the real and imaginary parts of an array of complex numbers.

In [12]:
ar = np.array([ 1.00000000+0.j, 0.70710678+0.70710678j])
print(f"Real part of array : {ar.real}")
print(f"Imaginary part of array : {ar.imag}")

Real part of array : [1.         0.70710678]
Imaginary part of array : [0.         0.70710678]


11. Write a Python program to find the number of elements of an array, length of one array element in bytes and total bytes consumed by the elements.


In [13]:
arr = np.array([1,4,6])
print(f"Size of the array : {arr.size}")
print(f"Length of one array element in bytes : {arr.itemsize}")
print(f"Total bytes consumed by the elements of the array : {arr.itemsize * arr.size}")

Size of the array : 3
Length of one array element in bytes : 4
Total bytes consumed by the elements of the array : 12


12. Write a Python program to find common values between two arrays

In [14]:
arr1 = np.array([0, 10, 20, 40, 60])
arr2 = np.array([10, 30, 40])
common = np.intersect1d(arr1,arr2)
print(f"Common Elements : {common}")


Common Elements : [10 40]


13. Write a Python program to find the set difference of two arrays

In [ ]:
arr1 = np.array([0, 10, 20, 40, 60, 80])
arr2 = np.array([10, 30, 40, 50, 70, 90])
common = np.setdiff1d(arr1,arr2)  
print(f"Set Difference : {common}")

Set Difference : [ 0 20 60 80]


14. Write a Python program to find the set exclusive-or of two arrays

In [ ]:
arr1 = np.array([0, 10, 20, 40, 60, 80])
arr2 = np.array([10, 30, 40, 50, 70, 90])
xor = np.setxor1d(arr1,arr2)  
print(f"Set Exclusive : {xor}")

Set Exclusive : [ 0 20 30 50 60 70 80 90]


15. Write a Python program compare two arrays using numpy.

In [17]:
a = np.array([1,3])
b = np.array([4,5])

print(f"a > b : {np.greater(a,b)}")
print(f"a >= b : {np.greater_equal(a,b)}")
print(f"a < b : {np.less(a,b)}")
print(f"a <= b : {np.less_equal(a,b)}")

a > b : [False False]
a >= b : [False False]
a < b : [ True  True]
a <= b : [ True  True]


15. Write a Python program to save a NumPy array to a text file.

In [18]:
arr = np.arange(10)
np.savetxt("array.txt", arr, fmt='%d')


16. Write a Python program to create a contiguous flattened array.

In [34]:
arr = np.array([[2, 4, 6],[6, 8, 10]])
arr = arr.ravel()
arr

array([ 2,  4,  6,  6,  8, 10])

17. Write a Python program to change the data type of an array

In [20]:
arr = np.array([[2, 4, 6],[6, 8, 10]])
arr = arr.astype("float64")
arr.dtype

dtype('float64')

18. Write a Python program to create a 3-D array with ones on a diagonal and zeros elsewhere.

In [21]:
ide = np.identity(3)
ide

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

19. Write a Python program to create a triangular matrix

In [22]:
np.tri(4,3,-1)

array([[0., 0., 0.],
       [1., 0., 0.],
       [1., 1., 0.],
       [1., 1., 1.]])

20. Write a Python program to concatenate two 2-dimensional arrays.


In [23]:
arr = [[0, 1, 3], [5, 7, 9]]
arr1 = [[0, 2, 4], [6, 8, 10]]

arr3 = np.concatenate((arr, arr1), axis=1)
arr3


array([[ 0,  1,  3,  0,  2,  4],
       [ 5,  7,  9,  6,  8, 10]])

21. Write a Python program to make an array immutable (read-only)

In [24]:
arr = np.array([1,2,3,4,5])
arr.setflags(write=False)

22. Write a Python program to create an array of (3, 4) shape, multiply every element value by 3 and display the new array.


In [25]:
arr = np.arange(12).reshape(3,4)
arr = arr * 3
arr

array([[ 0,  3,  6,  9],
       [12, 15, 18, 21],
       [24, 27, 30, 33]])

23. Write a Python program to convert a NumPy array into Python list structure

In [26]:
arr = np.array([[0, 1],[2, 3],[4, 5]])
arr = arr.tolist()
arr

[[0, 1], [2, 3], [4, 5]]

24. Write a Python program to convert a NumPy array into Python list structure (round to 3).


In [27]:
arr = np.array([0.26153123, 0.52760141, 0.5718299, 0.5927067, 0.7831874, 0.69746349, 0.35399976, 0.99469633, 0.0694458, 0.54711478])
arr = arr.round(3).tolist()
arr

[0.262, 0.528, 0.572, 0.593, 0.783, 0.697, 0.354, 0.995, 0.069, 0.547]

25. Write a Python program to suppresses the use of scientific notation for small numbers in numpy array

In [28]:
arr = np.array([ 1.60000000e-10, 1.60000000e+00, 1.20000000e+03, 2.35000000e-01])
np.set_printoptions(suppress=True,precision=3)
arr

array([   0.   ,    1.6  , 1200.   ,    0.235])

26. Write a Python program to how to add an extra column to an numpy array.

In [29]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr1 = np.array([[10], [20]])
arr = np.append(arr,arr1,axis=1)
arr

array([[ 1,  2,  3, 10],
       [ 4,  5,  6, 20]])

27. Write a Python program to remove specific elements in a numpy array.

In [30]:
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
indexArray = [1, 2, 5, 6, 7, 8, 9]

arr = arr[indexArray]
arr

array([ 20,  30,  60,  70,  80,  90, 100])